name: create-ecr-repository-action
description: Create Amazon ECR repository if not exist
author: int128

inputs:
  public:
    required: true
    description: set true to create into ECR Public registry
    default: 'false'
  delete:
    required: true
    description: set true to delete ECR
    default: 'false'
  repository:
    required: true
    description: repository name to create
  repo-policy:
    required: false
    description: path to repo policy file of the repository (optional)
  lifecycle-policy:
    required: false
    description: path to lifecycle policy file of the repository (optional)

outputs:
  repository-uri:
    description: URI of the repository, i.e. ACCOUNT.dkr.ecr.REGION.amazonaws.com/NAME

runs:
  using: 'node16'
  main: 'dist/index.js'
